---
.travis.yml:
  rubygems_api_key: "Jkn4btEyx/4gczEedWCl/dDFd0GsSNZ2ZI7VsY2hUlLDyaRr4JIRNj8szg7FD5jANa7dGLIzaut8lwcp015E7Oif1dIKEs5Wm4YH/7lW5ol3uH0eIuZZk/JpA3/YudrSywzftZHzievIxFOmGHZiAG2Isl2POGD7u9dtRmkIVI0="
